# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
	#define
	workspace = "TeamCityDemo.xcworkspace"

	before_all do
		cocoapods(
      repo_update: false,
      try_repo_update_on_error : true,
      use_bundle_exec: true
    )
    clear_dirived_data
  end

  desc "Run all the tests"

  lane: build_and_test do
    begin 
      scan(
        workspace: workspace,
        scheme: "TeamCityDemo"
      )
      on_succsess("")
    rescue => exception
        on_error(exception)
    end
  end
end
def on_succsess(message)
end
def on_error(exception)
end
